import Foundation

/// The badge artwork shipped in `Assets.xcassets/Medals`.
///
/// The renders come from the community catalogue of Apple Fitness award badges
/// (projects.peterwunder.de/achievements) — Blender re-creations of the models, textures
/// and stickers Apple uses for Limited Edition challenges. The originals are Apple's
/// property and are reproduced here as award artwork for this app.
enum MedalCatalog {
    static let all: [String] = [
        "sprout_star",
        "star_gold",
        "peak_wave_hex",
        "sunrise_leaf_shield",
        "sunburst",
        "laurel_star_navy",
        "night_sky",
        "galaxy_spiral",
        "crown_laurel_red",
        "leaf_ring",
        "clover",
        "crown_leaf_shield",
        "waves_blue",
        "ice_peak_hex",
        "laurel_star_silver",
        "mountains_brown",
        "peak_red_hex",
        "laurel_star_crimson",
        "lightning",
        "gear",
        "flask",
        "open_book",
        "puzzle",
        "bullseye",
        "sprout_sun",
        "handprint",
        "wave_arc",
        "burger",
        "popcorn",
        "mountain_sun_shield",
        "swirl_hex",
        "planet",
        "laurel_crown",
        "sprout",
        "blossom_teal",
        "laurel_teal",
        "snow_peak_shield",
        "desert_peak",
        "silver_peak_shield",
        "flame",
        "gem_crimson",
        "flame_crown",
        "snowflake_shield",
        "heart_shield",
        "sprout_shield",
        "raindrop_shield",
        "sun_flowers_shield",
        "sunrise_hills",
        "cloud_stars",
        "forest_peak",
        "calendar_night",
        "sunset_landscape",
        "crystal_blue",
        "laurel_wreath_red",
        "seasons_leaf_snow",
        "pine_snow",
        "rainbow_flower",
        "crown_grid",
        "trophy",
        "community_heart",
        "community_group",
        "community_blossom",
        "community_shield",
        "community_laurel",
        "snowflake_winter",
        "heart_bloom",
        "spring_growth",
        "rain_cloud",
        "blossom_pink",
        "sun_wave",
        "palm",
        "sunflower",
        "autumn_leaf",
        "moon_pines",
        "snowflake",
        "heart",
        "cherry_blossom",
        "raindrops",
        "leaves_green",
        "sun_leaves",
        "sunset_wave",
        "sun_swirl",
        "autumn_leaves",
        "moon_stars",
        "sun_clouds",
        "leaf_hex",
        "wave_blue",
        "compass_star",
        "snow_peak_blue_shield",
        "hills_sun",
        "laurel_shield_teal",
        "winged_star",
        "snowflake_ring",
        "calendar_rainbow",
        "calendar_moon",
        "trophy_gold",
        "leap_day_calendar",
        "birthday_cake",
        "pi_day",
        "lightsaber_planet",
        "friday_thirteenth_calendar",
        "pinata",
        "pumpkin",
        "christmas_wreath",
        "sunrise_celebration",
        "heart_bloom_pink",
        "mountain_flag",
        "cocktail_night",
        "error_404",
        "lucky_777",
        "one_oh_one",
        "thousand_flag",
        "loop_arrows",
        "calendar_checks",
        "terminal_one",
        "stopwatch_blue",
        "stopwatch_flame",
        "submission_board",
        "summit_path",
        "rubber_duck",
        "two_birds",
        "clock_flame",
        "alarm_clock",
        "language_bubbles",
        "chat_bubbles",
        "globe_airplane",
        "code_ribbons",
        "night_to_dawn",
        "gear_arrows",
        "bug_wrench",
        "airplane_offline",
        "recycle_leaf",
        "sunrise_meadow",
        "night_city",
    ]

    private static let lookup = Set(all)

    /// Deterministic pick for achievements the server hasn't assigned artwork to yet, so
    /// a badge never renders blank and never changes between launches.
    static func fallback(for key: String) -> String {
        guard !all.isEmpty else { return "" }
        var hash: UInt64 = 5381
        for byte in key.utf8 {
            hash = (hash &* 33) &+ UInt64(byte)
        }
        return all[Int(hash % UInt64(all.count))]
    }

    static func contains(_ slug: String) -> Bool { lookup.contains(slug) }
}
